# Generated by Django 3.2 on 2021-11-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Menus',
        ),
        migrations.RenameModel(
            old_name='Vote',
            new_name='Votes',
        ),
    ]
